apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-cards
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-cards
  template:
    metadata:
      labels:
        app: flash-cards
    spec:
      imagePullSecrets:
      - name: docker-registry
      nodeSelector:
        kubernetes.io/arch: arm64  # or arm64 depending on your node
      containers:
      - name: flash-cards
        image: yakovav/flash-cards-ops
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101 