apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flash-cards-dev

resources:
- ../../base

images:
- name: yakovav/flash-cards-ops
  newTag: arm64

patches:
- target:
    kind: Deployment
    name: flash-cards
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DEBUG
        value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: API_URL
        value: "/api"
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        kubernetes.io/arch: arm64
    - op: add
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1"
    - op: add
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: add
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: add
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
